### ISSUE TITLE
Visited

### ISSUE THREAD

**Issue by cbeauchesne** [cbeauchesne/campui#64]
```css
.home-view a:visited {
color:#1ab394;
}
```

**Comment by morrme** [comment]
Is this something you'd like placed in [this section](https://github.com/cbeauchesne/campui/blob/master/app/static/scss/campui.scss#L217)?

**Comment by cbeauchesne** [comment]
Exactly, it was a reminder.

**Comment by cbeauchesne** [comment]
By the way, I'm a little bit curious : by what chance did you got here?

**Comment by morrme** [comment]
@cbeauchesne searching for repos to contribute to. I'm new, so the practice is good for me. :smile:

**Comment by cbeauchesne** [comment]
Ok, enjoy your time on github! :smile:

**Comment by morrme** [comment]
@cbeauchesne thanks! i love it so far!
